<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>FSH.Modules.Products.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Products.Contracts</AssemblyName>
		<PackageId>FullStackHero.Modules.Products.Contracts</PackageId>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Domain\Events\" />
	</ItemGroup>
</Project>
