<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>FSH.Modules.Products</RootNamespace>
		<AssemblyName>FSH.Modules.Products</AssemblyName>
		<PackageId>FullStackHero.Modules.Products</PackageId>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
		<ProjectReference Include="..\Modules.Products.Contracts\Modules.Products.Contracts.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Application\Features\Queries\" />
	  <Folder Include="Domain\Enums\" />
	  <Folder Include="Domain\Events\" />
	  <Folder Include="Infrastructure\" />
	</ItemGroup>
</Project>
